/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        //SearchAmazon search = new SearchAmazon();
        //BookMyShow links = new BookMyShow();
        //WindowHandle windowHandle = new WindowHandle();
        //NestedFrames nf = new NestedFrames();
        LinkedinPost post = new LinkedinPost();

        //search.testCase01();
        //links.testCase01();
        //windowHandle.testCase01();
        //nf.testCase01();
        post.createPost();

        //search.endTest();
        //links.endTest();
        //windowHandle.endTest();
        //nf.endTest();
        post.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
