/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        //SearchAmazon search = new SearchAmazon();
        //BookMyShow links = new BookMyShow();
        WindowHandle windowHandle = new WindowHandle();


        //search.testCase01();
        //links.testCase01();
        windowHandle.testCase01();
    
        //search.endTest();
        //links.endTest();
        windowHandle.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
