/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.awt.AWTException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException, AWTException {
        
        //SearchAmazon search = new SearchAmazon();
        //BookMyShow links = new BookMyShow();
        //WindowHandle windowHandle = new WindowHandle();
        //NestedFrames nf = new NestedFrames();
        LinkedinPost post = new LinkedinPost();
        //ImageUrls i = new ImageUrls();
        //ImdbRatings imdb = new ImdbRatings();


        //search.testCase01();
        //links.testCase01();
        //windowHandle.testCase01();
        //nf.testCase01();
        post.createPost();
        //i.testCase01();
        //imdb.testCase01();

        //search.endTest();
        //links.endTest();
        //windowHandle.endTest();
        //nf.endTest();
        post.endTest();
        //i.endTest();
        //imdb.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException, AWTException {
        new App().getGreeting();
    }
}
